urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to

from helpers import here
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^project/', include('project.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)





urlpatterns += patterns('ywot.views',
    ### Web page:
    # Main
    url(r'^home/$', 'home', name='home'),
    
    # Accounts
    (r'^accounts/$', redirect_to, {'url': '/accounts/profile/'}),
    url(r'^accounts/profile/', 'profile', name='profile'),
    url(r'^accounts/logout/$', 'logout', name='logout'),
    (r'^accounts/private/', 'private'),
    (r'^accounts/configure/$', redirect_to, {'url': '/accounts/profile/'}),
    url(r'^accounts/configure/(.*)/$', 'configure', name='configure'),
    url(r'^accounts/configure/(beta/\w+)/$', 'configure', name='configure'),
    url(r'^accounts/member_autocomplete/$', 'member_autocomplete'),
    
    (r'^accounts/', include('registration.urls')),
    
    ### Worlds:
    # World management
    url(r'^ajax/protect/$', 'protect', name='protect'),
    url(r'^ajax/unprotect/$', 'unprotect', name='unprotect'),
    url(r'^ajax/coordlink/$', 'coordlink', name='coordlink'),
    url(r'^ajax/urllink/$', 'urllink', name='urllink'),
    

    # Worldviews
    ('^(\w*)$', 'yourworld'),
    ('^u/(\w*)$', 'yourworld'),
    ('^(beta/\w*)$', 'yourworld'),
    ('^(frontpage/\w*)$', 'yourworld'),
)

urlpatterns += patterns('',
    (r'^favicon\.ico$', redirect_to, {'url': '/static/ww.png'}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        ('^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': here('static')}),
    )

ywot/models.py
from django.contrib.auth.models import User
from django.db import models
from django.http import Http404
from lib import log
# from collections import Counter	

from lib.jsonfield import DictField


class World(models.Model):
	name = models.CharField(unique=True, max_length=255, blank=True)
		# Creating this index for much faster world lookups from World.get_or_create,
		# which are very common.
		# CREATE INDEX CONCURRENTLY world_name_upper ON ywot_world(UPPER(name));
	owner = models.ForeignKey(User, null=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	public_readable = models.BooleanField(default=True) # Otherwise whitelist
	public_writable = models.BooleanField(default=True) # Otherwise whitelist
	properties = DictField(default={}, blank=True)
	default_char = models.CharField(max_length=1, default=' ')

	prompt = models.TextField(blank=True)

	properties = DictField(default={})
	
	@staticmethod
	def get_or_create(name):
		"""Same interface as Model.get_or_create."""
		if '/' in name:
			# These are only created manually
			try:
				return (World.objects.get(name__iexact=name), False)
			except World.DoesNotExist:
				raise Http404

		# GAE worlds were case-sensitive. Until we figure out what to do about that, just return
		# the first one:
		worlds = World.objects.filter(name__iexact=name)
		if not len(worlds):
			return (World.objects.create(name=name), True)
		return (worlds[0], False)
	
	class Meta:
		ordering = ['name']
		
	def __unicode__(self):
		try:
			if self.name[0]=='u' and self.name[1]=='_':
				return self.name[2:] + "'s Personal World"
			return self.name
		except:
			return self.name
	
	def get_absolute_url(self):
		# MEDIA_ROOT # ?????????
		return '/' + self.name

class Tile(models.Model):
	# ROWS = 8
	# COLS = 16
	ROWS = 14
	COLS = 18
	
	LEN = ROWS*COLS
	world = models.ForeignKey(World)

	content = models.CharField(default=' '*LEN,  max_length=LEN)
	color = models.CharField(default='0'*LEN,  max_length=LEN)
	echos = models.CharField(default='0'*LEN,  max_length=LEN)

	# cursors = models.CharField(default='0'*LEN,  max_length=LEN)
	# sqlite> ALTER TABLE ywot_tile add cursors memo;

	tileY = models.IntegerField()
	tileX = models.IntegerField()
	properties = DictField(default={})

	new = models.IntegerField(default=1)

	# properties:
	# - protected (bool)
	# - cell_props[charY][charX] = {}
	
	created_at = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return "Tile in " +self.world.name 

	def save(self, *args, **kwargs):
		if self.new:
			self.content=self.world.default_char * self.LEN
			self.new=0;
		super(Tile, self).save(*args, **kwargs) # Call the "real" save() method.
		# do_something_else()
	
	def set_char(self, charY, charX, char, cid):
		from helpers import control_chars_set
		if char in control_chars_set:
			# TODO: log these guys again at some point
			char = ' '
		assert len(self.content) == self.ROWS*self.COLS
		assert len(self.color) == self.ROWS*self.COLS
		charY, charX = int(charY), int(charX)
		index = charY*self.COLS+charX
		self.content = self.content[:index] + char + self.content[index+1:]
		self.color = self.color[:index] + cid + self.color[index+1:]


		# add sid identifier 
		# if 'cell_props' not in self.properties:
		#     self.properties['cell_props'] = {}
		# if charY not in self.properties['cell_props']:
		#     self.properties['cell_props'][charY] = {}
		# if charX not in self.properties['cell_props'][charY]:
		#     self.properties['cell_props'][charY][charX] = {}
		# self.properties['cell_props'][charY][charX]['sid'] = sid
			# self.save()

		assert len(self.content) == self.ROWS*self.COLS
		assert len(self.color) == self.ROWS*self.COLS

	def get_density(self):
		density =0
		if self.content == ' '*self.LEN:
			return density
		else:
			for c in self.content:
				if c != ' ':
					density+=1
			return density
			# return scale(density, (0, 252), (0, 100))

	#average, meaning mode, not mean, ok?
	def get_average_color(self):
		return 0
		# common=Counter(self.color).most_common(2) #get the two most common chars
		# if len(common) ==1:  			#if theres only one common color, return it
		# 	return int(common[0][0])
		# else:
		# 	if common[0][0] == '0':
		# 		return int(common[1][0])  #if the most common is 0, return the second most common
		# 	else:
		# 		return int(common[0][0]) #otherwise return the most common


	# def get_average_color(self):
	# 	csum =0
	# 	count=0
	# 	for c in self.color:
	# 		if c != '0':
	# 			count+=1
	# 			csum += int(c)
	# 	if count ==0:
	# 		return 0
	# 	return (csum/count)

		
	class Meta:
		unique_together=[['world', 'tileY', 'tileX']]
		
class Edit(models.Model):
	user = models.ForeignKey(User, null=True)
	ip = models.IPAddressField(null=True)
	world = models.ForeignKey(World)
	time = models.DateTimeField(auto_now_add=True) # ADD INDEX:
		#CREATE INDEX CONCURRENTLY ywot_edit_time ON ywot_edit(time);
	content = models.TextField()
	
	class Meta:
		ordering = ['time']

	def __unicode__(self):
		if self.user:
			return self.user.username + " on " + self.world.name 
		else:
			return "somebody on " + self.world.name 
class Whitelist(models.Model):
	user = models.ForeignKey(User)
	world = models.ForeignKey(World)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	class Meta:
		unique_together=[['user', 'world']]
	
# Turns out we don't really need this
class UserWorld(models.Model):
	world = models.ForeignKey(World, null=True, blank=True)
	user = models.ForeignKey(User, null=True, blank=True)



def user_post_save(sender, instance, created, **kwargs):
	if created:
		world = World.objects.create(name='u_'+instance.username, public_readable=False, public_writable=False, owner=instance)
		uworld = UserWorld.objects.create(world=world, user=instance)



# def edit_post_save(sender, instance, created, **kwargs):
#     if instance.user:
#         personal_world_name ="u_"+instance.user.username
#         if (instance.world.name != personal_world_name):
#             personal_world= World.objects.get(name=personal_world_name)
#             personal_edit = instance
#             personal_edit.world = personal_world
#             personal_edit.save()
			# log.info('created a new personal world edit:')
			# log.info(personal_edit)

		# world = World.objects.create(name='user_'+instance.username, public_readable=False, public_writable=False, owner=instance)
		# uworld = UserWorld.objects.create(world=world, user=instance)

models.signals.post_save.connect(user_post_save, sender=User)

# models.signals.post_save.connect(edit_post_save, sender=Edit)


def scale(val, src, dst):
    """
    Scale the given value from the scale of src to the scale of dst.
    """
    return ((val - src[0]) / (src[1]-src[0])) * (dst[1]-dst[0]) + dst[0]


from django.contrib import admin
admin.site.register(World)
admin.site.register(Tile)
admin.site.register(UserWorld)
admin.site.register(Edit)

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
        <title>{% block title %}WrittenWorld{% endblock %}</title>

        <!-- <link rel="stylesheet" href="/static/css/blueprint/screen.css" type="text/css" media="screen, projection"> -->
        <link rel="stylesheet" href="/static/css/blueprint/print.css" type="text/css" media="print">    
        <!--[if lt IE 8]><link rel="stylesheet" href="/static/css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
        <link rel="stylesheet" type="text/css" href="/static/css/site.css?v=1">
	    <link type="text/css" rel="stylesheet" href="/static/yourworld.css?v=1">
        <link rel="shortcut icon" href="/static/ww.png">
        {% block endhead %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <div class="span-19">
                <div id="topbar" class="span-19 last">
                    {% if user.is_authenticated %}
                        Logged in as <a href="{% url profile %}">{{ user }}</a>
                    {% endif %}
                    {% if user.is_authenticated %}
                        | <a href="{% url profile %}">Your Worlds</a>
                        | <a href="{% url logout %}">Logout</a>
                    {% else %}
                        <a href="{% url home %}">Home</a>
                        | <a href="{% url auth_login %}">Login</a>
                    {% endif %}
                        | <a href="/">World</a> 

                </div>

                <div class="span-19 last">
                    {% block header %}{% endblock %}
                </div>

                <div class="span-14 float_left text">
                    {% block content %}{% endblock %}
                </div>
                <div id="updates">
	                <div id="updates_title">
	                    Recent Site Updates<br>
	                    <a class="small" href="http://www.twitter.com/yourworldoftext">via Twitter</a>
	                </div>
	                <div id="updates_container"><span class="loading">Loading...</span></div>
	            </div>
            </div>

        </div><!-- container -->
        
        <script type="text/javascript" src="/static/jquery-1.3.2.min.js"></script>
        <script src="http://twitterjs.googlecode.com/svn/trunk/src/twitter.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="/static/twitterfeed.js"></script>
        {% block endbody %}{% endblock %}
<!-- Google analytics -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-27491690-1']);
  _gaq.push(['_setDomainName', 'writtenworld.org']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- End Google analytics -->
    </body>
</html>

templates/configure.html
{% extends "base.html" %}

{% block title %}
	Options for "{{ world }}" | {{ block.super }}
{% endblock %}

{% block endhead %}
<link rel="stylesheet" type="text/css" href="/static/jquery.autocomplete.css">
{% endblock %}

{% block header %}
	<h1>Options for "{{ world }}"</h1>
	<span><a href="{% url profile %}">« Back to profile</a></span>
{% endblock %}

{% block content %}
	<div class="content_set">
		<div class="content_set_title">Access</div>
		<div class="content_set_content">
			<form method="POST" action=".">{% csrf_token %}
			Visitors who aren't members: <select name="public_perm">
				<option value="none"{% ifequal public_perm "none" %} selected{% endifequal %}>cannot view this world at all.</option>
				<option value="read"{% ifequal public_perm "read" %} selected{% endifequal %}>can view this world, but not edit it.</option>
				<option value="write"{% ifequal public_perm "write" %} selected{% endifequal %}>can view this world and edit it.</option>
			</select>
			<input type="hidden" name="form" value="public_perm">
			<input type="submit" value="Submit">
			</form>
		</div>
	</div>

<!-- 	<div class="content_set clearfix">
		<div class="content_set_title">Features</div>
		<div class="content_set_content">

			<div class="set_description">
				Control what features are usable on your world. 
				When a feature is set to "enabled", any visitor to the world can use it. Otherwise, it is only available for the owner.
			</div>
			<form method="POST" action=".">{% csrf_token %}
			<table id="feature_choices">
				<tr>
					<td class="feature_name">Go to coordinates</td>
					<td>
						<select name="go_to_coord">
							<option value="0" {% if not world.properties.features.go_to_coord %}selected{% endif %}>disabled</option>
							<option value="1" {% if world.properties.features.go_to_coord %}selected{% endif %}>enabled</option>
						</select>
					</td>
					<td class="feature_description">
						Transports you to any given coordinates on a world. 
					</td>
				</tr>
				<tr>
					<td class="feature_name">Create link to coordinates</td>
					<td>
						<select name="coordLink">
							<option value="0" {% if not world.properties.features.coordLink %}selected{% endif %}>disabled</option>
							<option value="1" {% if world.properties.features.coordLink %}selected{% endif %}>enabled</option>
						</select>
					</td>
					<td class="feature_description">
						Make a letter link to a different part of the world. 
					</td>
				</tr>
				<tr>
					<td class="feature_name">Create link to URL</td>
					<td>
						<select name="urlLink">
							<option value="0" {% if not world.properties.features.urlLink %}selected{% endif %}>disabled</option>
							<option value="1" {% if world.properties.features.urlLink %}selected{% endif %}>enabled</option>
						</select>
					</td>
					<td class="feature_description">
						Make a letter link to a URL.
					</td>
				</tr>

			</table>
			<input type="hidden" name="form" value="features">
			<span style="float:right">
			<input type="submit" value="Submit">
			</span>
			</form>
		</div>
	</div> -->

	<div class="content_set">
		<div class="content_set_title">Members</div>
		<div class="content_set_content">
			{% if members %}
				<ul>
					<form method="POST" action=".">{% csrf_token %}
					<input type="hidden" name="form" value="remove_member">
					{% for member in members %}
						<li>{{ member }} <input type="submit" name="remove_{{ member }}" value="Remove {{ member }}">
					{% endfor %}
					</form>
				</ul>
			{% else %}
				<span style="margin-left:1em">None</span>
			{% endif %}
			{% if add_member_message %}<div><i>{{ add_member_message }}</i></div>{% endif %}
			<div style="margin-top:.3em">
				<form method="POST" action=".">{% csrf_token %}
				<label for="choose_member">Add a member: </label>
				<input id="choose_member" type="text" name="add_member" value="">
				<input type="hidden" name="form" value="add_member">
				<input type="submit" value="Submit">
			</div>
			</form>
		</div>
	</div>
{% endblock %}
{% block endbody %}
<script type="text/javascript" src="/static/jquery.autocomplete.min.js"></script>
<script type="text/javascript" src="/static/profile.js"></script>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}
    Homepage | {{ block.super }}
{% endblock %}

{% block header %}
	<div class="text">
		<img class="logo" src="/static/ww_big.png">
    	<h1>About this project</h1>
	</div>
{% endblock %}

{% block content %}
        <p>    
		Hi There, 
		</p><p>
		We’re <a href="http://zachschwartz.com">Zach Schwartz</a>, <a href="http://www.bravomartin.cl/">Martín Bravo</a>, <a href="http://nara-designs.com">Nara Kasbergen</a>, Rachel Slaff, and Ruth Spencer, students in <a href="http://shirky.com/">Clay Shirky’s</a> Designing Conversational Spaces course at NYU’s <a href="http://itp.nyu.edu/itp/">ITP</a>. </p>
		<p>
		The Written World is an experiment, based on <a href="http://www.yourworldoftext.com/">yourworldoftext</a>. We’ve placed a free-form text canvas on top of Google maps and added geolocation* functionality to see what happens when we combine online chat with the pre-existing relationships that are inherent to physical location and real-world places. For now, we’ve limited WW to New York users, but will open it up to everyone soon.
		</p>
		<p>
		You’ll automatically be positioned at your current location*. Want to travel? Type your way over to different areas or click and drag to scroll. To move the cursor, use the arrow keys, or double click.
		</p><p>
		That’s it. The rules of the site are for you to create (or ignore). So what are you waiting for? Go explore! 
		</p><p>
		<small>
		*Geolocation is an experimental feature in html5 and may not work in all browsers, locations, operating systems, and weather systems. On our experience, <a href="http://www.firefox.com">Firefox</a> is the browser that works better. Sorry.</small>
		</p>

	<br>
	<a href="/"> Go to the common world!</a>

{% endblock %}

templates/private.html
{% extends "base.html" %}

{% block title %}
    Profile | {{ block.super }}
{% endblock %}

{% block header %}
    <h1>Private</h1>
{% endblock %}

{% block content %}
    <div class="text">
		<p>Sorry, the owner of that world has made it only visible to members.
			{% if user.is_authenticated %}
				<a href="/">Go back to the main world</a>, perhaps.
			{% else %}
				Perhaps <a href="{% url auth_login %}">login </a> or <a href="{% url registration_register %}">create an account</a>. 
				</p><p>
				Or, <a href="/">go back to the main world</a>.
			{% endif %}
		</p>
    </div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block title %}
    Profile | {{ block.super }}
{% endblock %}

{% block header %}
    <h1>Your account</h1>
{% endblock %}

{% block content %}
<!-- 	<div class="content_set">
		<div class="content_set_title">Claim a World</div>
		<div class="content_set_content">
			{% if message %}
				<span style="font-size:80%"><i>{{ message }}</i></span>
			{% endif %}
			<form method="POST" action=".">{% csrf_token %}
				World name: 
				<input type="text" name="worldname" value="">
				<input type="submit" value="Submit">
			</form>
		</div>
	</div> -->

	{% if worlds_owned %}
		<div class="content_set">
			<div class="content_set_title">Worlds you own</div>
			<div class="content_set_content">
				<ul>
					{% for world in worlds_owned %}
					<li><a href="{{ world.get_absolute_url }}">{{ world }}</a>, 
						{% if world.public_writable %}
							publicly editable,
						{% else %}
							{% if world.public_readable %}
								publicly visible (but not editable),
							{% else %}
								not publicly visible,
							{% endif %}
						{% endif %}
						{% with world.whitelist_set.count as num_wl %}
							{{ num_wl }} member{{ num_wl|pluralize }}.
						{% endwith %}

						<a href="{% url configure world.name %}">options</a>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	{% endif %}

	<a href="/">Go to the common world.</a>
	{% if memberships %}
		<div class="content_set">
			<div class="content_set_title">World you belong to</div>
			<div class="content_set_content">
				<ul>
				{% for world in memberships %}
					<li><a href="{{ world.get_absolute_url }}">{{ world }}</a>
				{% endfor %}
				</ul>
			</div>
		</div>
	{% endif %}

{% endblock %}

templates/yourworld.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <title>Written World</title>
    <meta name=”viewport” content=”user-scalable=false” />


    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale = 1.0" />
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8"> 
    <link type="text/css" rel="stylesheet" href="/static/yourworld.css?v=1">
	<link rel="shortcut icon" href="/static/ww.png" />

</head>
<body>
<div id="topbar" class="ui">
  <!-- <div id="topbarAbout"> <a href="#">what is this?</a></div> -->
    <div id="topbar_inner">
        <span id="paused" class="ui-vis tab">Paused</span>
        <div id="announce" class="ui-vis"></div>
		<div id="login_btn" class="button"> <a  href="/accounts/login/">get your own world</a></div>
		<!-- <div id="takeme_btn" class="button"> <a class="travel" address="New York City" href="#">take me to NYC</a></div> -->

        <!-- <span id="menu" class="ui-vis tab menu">Menu <span style="font-size:50%">▼</span></span> -->
    </div>
</div>
<div id="nav" class="ui menu ui-vis">
    <ul>
        <li>
            <a href="{% url home %}" target="_blank">About&nbsp;<img src="/static/Icon_External_Link.png"></a>
        </li>
    </ul>
</div>
<div id="coords" class="ui ui-vis">
    X: <span id="coord_X"></span>
    Y: <span id="coord_Y"></span>
</div>

<!-- <h1 id="loading">Loading...</h1> -->
<div id="geoReminder">
	<span class="arrow"><img src="/static/geoarrow.png" /> </span>
    <h3>Loading &amp; Finding Your Location...</h3> 
        <p>You must allow us to use your location when your browser asks.</p><p> Otherwise, the site won't really work.</p>
</div>
<div id="aboutOverlay">
	<div class="closeme"></div>

	<img class="logo" src="/static/writtenworld.png">
<p>    
Hi There, 
</p><p>
We’re Zach Schwartz, Martín Bravo, Nara Kasbergen, Rachel Slaff, and Ruth Spencer, students in <a href="http://shirky.com/">Clay Shirky’s</a> Designing Conversational Spaces course at NYU’s <a href="http://itp.nyu.edu/itp/">ITP</a>. </p>
<p>
The Written World is an experiment, based on <a href="http://www.yourworldoftext.com/">yourworldoftext</a>. We’ve placed a free-form text canvas on top of Google maps and added geolocation* functionality to see what happens when we combine online chat with the pre-existing relationships that are inherent to physical location and real-world places. For now, we’ve limited WW to New York users, but will open it up to everyone soon.
</p>
<p>
You’ll automatically be positioned at your current location*. Want to travel? Type your way over to different areas or click and drag to scroll. To move the cursor, use the arrow keys, or double click.
</p><p>
That’s it. The rules of the site are for you to create (or ignore). So what are you waiting for? Go explore! 
</p><p>
<small>
*Geolocation is an experimental feature in html5 and may not work in all browsers, locations, operating systems, and weather systems. Sorry.</small>
</p>
</div>


<div id="loadingIndicator">
	<div class="closeme"></div>
	
    <img class="logo" src="/static/writtenworld.png">
    <!-- <h1>{{ world.name|default:"" }}</h1> -->

    {{world.prompt|safe}}

</div>

<div id="about_btn" class="button"> <a href="/home/">about this thing</a></div>

<div id="mapcanvas"></div>


<script type="text/javascript" src="/static/jquery-1.3.2.min.js"></script>

<script type="text/javascript">
var usercolor;
  $(function() {
    //implicit global is so silly
     properties = {{ properties|safe }};
   color = "{{ color }}";
	 usercolor = "{{ color }}";

  });
</script>

<!-- OUR CODE -->
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=geometry&sensor=false"></script>
<script type="text/javascript" src="/static/mapstyles.js"></script>
<script type="text/javascript" src="/static/owot.js"></script>


<!-- END OUR CODE -->

<script type="text/javascript" src="/static/jquery-ui-1.7.2.custom.min.js"></script>
<script type="text/javascript" src="/static/BrowserDetect.js"></script>
<!-- <script type="text/javascript" src="/static/jquery.scrollview.js"></script> -->
<script type="text/javascript" src="/static/jquery.droppy.js"></script>
<!-- <script type="text/javascript" src="/static/jquery.simplemodal-1.3.3.mod.js"></script> -->

<!-- <script type="text/javascript" src="/static/yourworld.js?v=4"></script> -->
<script type="text/javascript">
  $(function() {
    var menu = $.Menu($('#menu'), $('#nav'));
    var  state = {{ state|safe }};
    InitWorld(document.getElementById('yourworld'), menu, state);

  });
</script>




<!-- Google analytics -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-27491690-1']);
  _gaq.push(['_setDomainName', 'writtenworld.org']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- End Google analytics -->

</body>
</html>